// This file was generated by prisma-enums, do not edit manually.

export const Role = {
  ADMIN: "ADMIN",
  USER: "USER",
} as const;
export type Role = (typeof Role)[keyof typeof Role];

export const Status = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
} as const;
export type Status = (typeof Status)[keyof typeof Status];
